# Generated by Django 5.1 on 2024-10-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile Table'},
        ),
    ]
