# Generated by Django 5.1 on 2024-10-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0006_alter_profile_address_alter_profile_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('invoice_id', models.CharField(blank=True, max_length=100)),
                ('payer_id', models.CharField(blank=True, max_length=100)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.dish')),
            ],
            options={
                'verbose_name_plural': 'Order Table',
            },
        ),
    ]
